name: generate animation

on:
  schedule:
      - cron: "0 0 * * 1"    # run automatically every week, Monday at midnight
      # - cron: "* * * * *" # run every minute (for testing only, remove for production)
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: generate grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: DinethShakya23
          outputs: |
            dist/grid-snake.svg
            dist/grid-snake-dark.svg?palette=github-dark
      
      - name: Commit and push the animation 
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "New SVGs were generated"
            git push
          fi